priorities:
  - id: highest
    short: A
    name: Highest
    color: isi-nanti
  - id: high
    short: B
    name: High
    color: isi-nanti
  - id: medium
    short: C
    name: Medium
    color: isi-nanti
  - id: low
    short: D
    name: Low
    color: isi-nanti
  - id: lowest
    short: E
    name: Lowest
    color: isi-nanti

statuses:
  - id: active
    name: Active
    emoji: ðŸ”µ
  - id: in-progress
    name: In Progress
    emoji: ðŸŸ¢
  - id: done
    name: Done
    emoji: âš«
  - id: cancelled
    name: Cancelled
    emoji: ðŸ”´
  - id: archive
    name: Archive
    emoji: ðŸŸ£

